### ISSUE TITLE
Add tests | Coverage checklist

### ISSUE THREAD

**Issue by kaynetik** [go-oas/docs#2]
- [x] Add a few example tests

1. [x] Routing 100% + Quick
2. [x] Annotations 91% (and quick tbd)
3. [x] Build
4. [x] Caller 100% + Quick
5. [x] Server
6. [x] Model Transformers
7. [x] Models - `New() OAS`

## Bonus:
- [ ] Add benchmarks for possible chokepoints
