### ISSUE TITLE
[RFC] Possible milestones?

### ISSUE THREAD

**Issue by kaynetik** [go-oas/docs#5]
Few RFCs proposed:

- [x] Postman support (build & push via PM API)
- [x] Go tests conversion to Cypress/Katalon suites (convert mocked unit tests into e2e tests)
- [x] Full on-run support for swagger, no CLI to "generate & serve", just run & enjoy
